[tools]
maven = "3"
python = "3"
node = "24"
java = "graalvm-community-25"
grpcurl = "latest"
k6 = "latest"
minikube = "latest"

[tasks.format]
description = "Format pom.xml and Java code"
dir = "./api"
run = "mvn spotless:apply"