# Quarkus
## Devservices
quarkus.datasource.dev-ui.allow-sql=true
## Logging
quarkus.log.console.json.enabled=false
quarkus.log.category."org.hibernate.session.metrics".level=DEBUG
## Flyway
quarkus.flyway.clean-disabled=false
quarkus.flyway.clean-at-start=true
## Hibernate
quarkus.hibernate-orm.statistics=true
quarkus.hibernate-orm.log-session-metrics=true
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true
quarkus.hibernate-orm.log.highlight-sql=true