# Logging
quarkus.log.console.json.enabled=false
quarkus.log.category."org.hibernate.session.metrics".level=DEBUG
# Health
quarkus.smallrye-health.ui.enabled=false
# OpenApi
quarkus.swagger-ui.enabled=false
# Flyway
quarkus.flyway.clean-disabled=false
quarkus.flyway.clean-at-start=true
# JobRunr
quarkus.jobrunr.dashboard.enabled=false