# Quarkus
## Devservices
quarkus.datasource.dev-ui.allow-sql=true
## Logging
quarkus.log.console.json.enabled=false
quarkus.log.category."org.hibernate.session.metrics".level=INFO
## Flyway
quarkus.flyway.clean-disabled=false
quarkus.flyway.clean-at-start=true
## Hibernate
quarkus.hibernate-orm.statistics=false
quarkus.hibernate-orm.log-session-metrics=false
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.log.highlight-sql=false