/**
 * Automatically generated by @grafana/openapi-to-k6: 0.4.1
 * Do not edit manually.
 * library-api API
 * Service version: 1.0.0-SNAPSHOT
 */
import { URL, URLSearchParams } from "https://jslib.k6.io/url/1.0.0/index.js";

import http from "k6/http";
import type { Params, Response } from "k6/http";

export interface AccountDto {
  id?: Uuid;
  username?: string;
  roles?: string[];
  active?: boolean;
  createdAt?: Instant;
  updatedAt?: Instant;
}

export interface AccountMeResponse {
  jwt?: JsonWebToken;
  account?: AccountDto;
}

export interface AuthorRestDto {
  id?: string;
  openLibraryKey?: string;
  name?: string;
  personalName?: string;
  alternateNames?: string[];
  uris?: string[];
  bio?: string;
  location?: string;
  birthDate?: string;
  deathDate?: string;
  wikipedia?: string;
  links?: string[];
  books?: string[];
  works?: string[];
}

/**
 * HTTP Problem Response according to RFC9457 and RFC7807
 */
export interface HttpProblem {
  /** A optional URI reference that identifies the problem type */
  type?: string;
  /** A optional, short, human-readable summary of the problem type */
  title?: string;
  /** The HTTP status code for this occurrence of the problem */
  status?: number;
  /** A optional human-readable explanation specific to this occurrence of the problem */
  detail?: string;
  /** A URI reference that identifies the specific occurrence of the problem */
  instance?: string;
  [key: string]: unknown;
}

/**
 * HTTP Validation Problem Response according to RFC9457 and RFC7807
 */
export interface HttpValidationProblem {
  /** A optional URI reference that identifies the problem type */
  type?: string;
  /** A optional, short, human-readable summary of the problem type */
  title?: string;
  /** The HTTP status code for this occurrence of the problem */
  status?: number;
  /** A optional human-readable explanation specific to this occurrence of the problem */
  detail?: string;
  /** A URI reference that identifies the specific occurrence of the problem */
  instance?: string;
  /** List of validation constraint violations that occurred */
  violations?: Violation[];
  [key: string]: unknown;
}

export type Instant = string;

export interface JobScheduledDto {
  value?: Uuid;
}

export interface JsonWebToken {
  name?: string;
  rawToken?: string;
  issuer?: string;
  audience?: string[];
  subject?: string;
  tokenID?: string;
  expirationTime?: number;
  issuedAtTime?: number;
  groups?: string[];
  claimNames?: string[];
}

export interface JwtToken {
  value?: string;
}

export interface LoginRequest {
  username?: string;
  password?: string;
}

export type OpenLibraryType =
  (typeof OpenLibraryType)[keyof typeof OpenLibraryType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OpenLibraryType = {
  AUTHOR: "AUTHOR",
  WORK: "WORK",
  EDITION: "EDITION",
} as const;

export interface RefreshRequest {
  username?: string;
  refreshToken?: string;
}

export interface RefreshToken {
  value?: string;
  expiresIn?: Instant;
}

export interface SignupRequest {
  username?: string;
  password?: string;
}

export interface TokenResponse {
  accessToken?: JwtToken;
  refreshToken?: RefreshToken;
}

/**
 * @pattern [a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}
 */
export type Uuid = string;

/**
 * Validation constraint violation details
 */
export interface Violation {
  /** The field for which the validation failed */
  field?: string;
  /** Part of the http request where the validation error occurred such as query, path, header, form, body */
  in?: string;
  /** Description of the validation error */
  message?: string;
}

export type GetApiV1JobrunrProcessTypeParams = {
  /**
   * @maximum 5000
   */
  limit?: number;
};

/**
 * This is the base client to use for interacting with the API.
 */
export class LibraryApiAPIClient {
  private cleanBaseUrl: string;
  private commonRequestParameters: Params;

  constructor(clientOptions: {
    baseUrl: string;
    commonRequestParameters?: Params;
  }) {
    this.cleanBaseUrl = clientOptions.baseUrl.replace(/\/+$/, "");

    this.commonRequestParameters = clientOptions.commonRequestParameters || {};
  }

  /**
   * @summary Login
   */
  postApiV1AccountsLogin(
    loginRequest: LoginRequest,
    requestParameters?: Params,
  ): {
    response: Response;
    data: TokenResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/api/v1/accounts/login`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(loginRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "PostApiV1AccountsLogin",
    };
  }

  /**
   * @summary Me
   */
  getApiV1AccountsMe(requestParameters?: Params): {
    response: Response;
    data: AccountMeResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/api/v1/accounts/me`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "GetApiV1AccountsMe",
    };
  }

  /**
   * @summary Refresh
   */
  postApiV1AccountsRefresh(
    refreshRequest: RefreshRequest,
    requestParameters?: Params,
  ): {
    response: Response;
    data: TokenResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/api/v1/accounts/refresh`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(refreshRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "PostApiV1AccountsRefresh",
    };
  }

  /**
   * @summary Signup
   */
  postApiV1AccountsSignup(
    signupRequest: SignupRequest,
    requestParameters?: Params,
  ): {
    response: Response;
    data: TokenResponse;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/api/v1/accounts/signup`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      k6url.toString(),
      JSON.stringify(signupRequest),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "PostApiV1AccountsSignup",
    };
  }

  /**
   * @summary Find By Id
   */
  getApiV1AuthorsId(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: AuthorRestDto;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/api/v1/authors/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "GetApiV1AuthorsId",
    };
  }

  /**
   * @summary Schedule File Download
   */
  getApiV1JobrunrDownloadType(
    type: OpenLibraryType,
    requestParameters?: Params,
  ): {
    response: Response;
    data: JobScheduledDto;
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl + `/api/v1/jobrunr/download/${type}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "GetApiV1JobrunrDownloadType",
    };
  }

  /**
   * @summary Schedule File Import
   */
  getApiV1JobrunrImportType(
    type: OpenLibraryType,
    requestParameters?: Params,
  ): {
    response: Response;
    data: JobScheduledDto;
    operationId: string;
  } {
    const k6url = new URL(this.cleanBaseUrl + `/api/v1/jobrunr/import/${type}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      k6url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "GetApiV1JobrunrImportType",
    };
  }

  /**
   * @summary Schedule Staging Processing
   */
  getApiV1JobrunrProcessType(
    type: OpenLibraryType,
    params?: GetApiV1JobrunrProcessTypeParams,
    requestParameters?: Params,
  ): {
    response: Response;
    data: JobScheduledDto;
    operationId: string;
  } {
    const k6url = new URL(
      this.cleanBaseUrl +
        `/api/v1/jobrunr/process/${type}` +
        `?${new URLSearchParams(params).toString()}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("GET", k6url.toString(), undefined, {
      ...mergedRequestParameters,
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
      operationId: "GetApiV1JobrunrProcessType",
    };
  }

  /**
   * Merges the provided request parameters with default parameters for the client.
   *
   * @param {Params} requestParameters - The parameters provided specifically for the request
   * @param {Params} commonRequestParameters - Common parameters for all requests
   * @returns {Params} - The merged parameters
   */
  private _mergeRequestParameters(
    requestParameters?: Params,
    commonRequestParameters?: Params,
  ): Params {
    return {
      ...commonRequestParameters, // Default to common parameters
      ...requestParameters, // Override with request-specific parameters
      headers: {
        ...(commonRequestParameters?.headers || {}), // Ensure headers are defined
        ...(requestParameters?.headers || {}),
      },
      cookies: {
        ...(commonRequestParameters?.cookies || {}), // Ensure cookies are defined
        ...(requestParameters?.cookies || {}),
      },
      tags: {
        ...(commonRequestParameters?.tags || {}), // Ensure tags are defined
        ...(requestParameters?.tags || {}),
      },
    };
  }
}
